// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package messages

import "strconv"

type Emp byte

const (
	EmpNONE  Emp = 0
	Empstaff Emp = 1
	EmpPass  Emp = 2
)

var EnumNamesEmp = map[Emp]string{
	EmpNONE:  "NONE",
	Empstaff: "staff",
	EmpPass:  "Pass",
}

var EnumValuesEmp = map[string]Emp{
	"NONE":  EmpNONE,
	"staff": Empstaff,
	"Pass":  EmpPass,
}

func (v Emp) String() string {
	if s, ok := EnumNamesEmp[v]; ok {
		return s
	}
	return "Emp(" + strconv.FormatInt(int64(v), 10) + ")"
}
