//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: message

package messages

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for GetInfo service
type GetInfoClient interface{
  GetPerson(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* Person, error)  
}

type getInfoClient struct {
  cc *grpc.ClientConn
}

func NewGetInfoClient(cc *grpc.ClientConn) GetInfoClient {
  return &getInfoClient{cc}
}

func (c *getInfoClient) GetPerson(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* Person, error) {
  out := new(Person)
  err := grpc.Invoke(ctx, "/messages.GetInfo/GetPerson", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for GetInfo service
type GetInfoServer interface {
  GetPerson(context.Context, *Name) (*flatbuffers.Builder, error)  
}

func RegisterGetInfoServer(s *grpc.Server, srv GetInfoServer) {
  s.RegisterService(&_GetInfo_serviceDesc, srv)
}

func _GetInfo_GetPerson_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(Name)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(GetInfoServer).GetPerson(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/messages.GetInfo/GetPerson",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(GetInfoServer).GetPerson(ctx, req.(* Name))
  }
  return interceptor(ctx, in, info, handler)
}


var _GetInfo_serviceDesc = grpc.ServiceDesc{
  ServiceName: "messages.GetInfo",
  HandlerType: (*GetInfoServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "GetPerson",
      Handler: _GetInfo_GetPerson_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

